set(T ogt_util)
add_library(${T} STATIC ogt_util.c)
target_include_directories(${T} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR} ${STB_IMAGE_DIR})
target_compile_definitions(${T} PRIVATE GLFW_INCLUDE_NONE)
target_link_libraries(${T} PUBLIC glad glfw OpenGL::GL cglm)
target_compile_options(${T} PRIVATE -Wall -Wextra -Wpedantic)
